version: '3.8'

services:
  axtech-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axtech-app
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://axtech.app
      - NEXT_PUBLIC_API_URL=https://axtech.app/api
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - app-data:/app/data
    networks:
      - axtech-network

  # Uncomment if you want to add a database
  # db:
  #   image: postgres:14-alpine
  #   container_name: axtech-db
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=axtech
  #     - POSTGRES_PASSWORD=your_secure_password
  #     - POSTGRES_DB=axtech_db
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - axtech-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U axtech"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  axtech-network:
    driver: bridge

volumes:
  app-data:
  # db-data:
